In [1]:
from langchain_community.document_loaders import TextLoader  # langchain to connect different ai systems into working system.
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [2]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")

In [3]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [4]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [5]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter

raw_documents = TextLoader(
    "../tagged_description.txt",
    encoding="utf-8"
).load()

text_splitter = CharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    separator="\n"
)

documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 500
Created a chunk of size 1214, which is longer than the specified 500
Created a chunk of size 960, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 881, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 1189, which is longer than the specified 500
Created a chunk of size 513, which is longer than the specified 500
Created a chunk of size 752, which is longer than the specified 500
Created a chunk of size 728, which is longer than the specified 500
Created a chunk of size 721, which is longer than the specified 500
Created a chunk of size 1267, which is longer than the specified 500
Created a chunk of size 681, which is longer than the specified 500
Created a chunk of size 553, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 787, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 563, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 614, which is longer than the specified 500
Created a chunk of size 887, which is longer than the specified 500
Created a chunk of size 693, which is longer than the specified 500
Created a chunk of size 2010, which is longer than the specified 500
Created a chunk of size 520, which is longer than the specified 500
Created a chunk of size 647, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 686, which is longer than the specified 500
Created a chunk of size 548, which is longer than the specified 500
Created a chunk of size 1225, which is longer than the specified 500
Created a chunk of size 1184, which is longer than the specified 500
Created a chunk of size 1214, which is longer than the specified 500
Created a chunk of size 1191, which is longer than the specified 500
Created a chunk of size 1057, which is longer than the specified 500
Created a chunk of size 688, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 766, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 899, which is longer than the specified 500
Created a chunk of size 1270, which is longer than the specified 500
Created a chunk of size 558, which is longer than the specified 500
Created a chunk of size 1635, which is longer than the specified 500
Created a chunk of size 777, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 514, which is longer than the specified 500
Created a chunk of size 958, which is longer than the specified 500
Created a chunk of size 1132, which is longer than the specified 500
Created a chunk of size 1325, which is longer than the specified 500
Created a chunk of size 851, which is longer than the specified 500
Created a chunk of size 801, which is longer than the specified 500
Created a chunk of size 1119, which is longer than the specified 500
Created a chunk of size 836, which is longer than the specified 500
Created a chunk of size 732, which is longer than the specified 500
Created a chunk of size 1195, which is longer than the specified 500
Created a chunk of size 710, which is longer than the specified 500
Created a chunk of size 773, which is longer than the specified 500
Created a chunk of size 766, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 2012, which is longer than the specified 500
Created a chunk of size 1286, which is longer than the specified 500
Created a chunk of size 1231, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 750, which is longer than the specified 500
Created a chunk of size 1242, which is longer than the specified 500
Created a chunk of size 912, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 1126, which is longer than the specified 500
Created a chunk of size 1073, which is longer than the specified 500
Created a chunk of size 1318, which is longer than the specified 500
Created a chunk of size 2834, which is longer than the specified 500
Created a chunk of size 570, which is longer than the specified 500
Created a chunk of size 1141, which is longer than the specified 500
Created a chunk of size 1004, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 710, which is longer than the specified 500
Created a chunk of size 2510, which is longer than the specified 500
Created a chunk of size 954, which is longer than the specified 500
Created a chunk of size 639, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 793, which is longer than the specified 500
Created a chunk of size 1422, which is longer than the specified 500
Created a chunk of size 1083, which is longer than the specified 500
Created a chunk of size 1144, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 790, which is longer than the specified 500
Created a chunk of size 1086, which is longer than the specified 500
Created a chunk of size 874, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 806, which is longer than the specified 500
Created a chunk of size 1812, which is longer than the specified 500
Created a chunk of size 1830, which is longer than the specified 500
Created a chunk of size 1064, which is longer than the specified 500
Created a chunk of size 955, which is longer than the specified 500
Created a chunk of size 1180, which is longer than the specified 500
Created a chunk of size 1284, which is longer than the specified 500
Created a chunk of size 1642, which is longer than the specified 500
Created a chunk of size 757, which is longer than the specified 500
Created a chunk of size 1930, which is longer than the specified 500
Created a chunk of size 872, which is longer than the specified 500
Created a chunk of size 2008, which is longer than the specified 500
Created a chunk of size 2285, which is longer than the specified 500
Created a chunk of size 1003, which is longer than the specified 500
Created a chunk of size 577, which is longer than the specified 500
Created a chunk of size 1142, which is longer than the specified 500
Created a chunk of size 557, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500
Created a chunk of size 1086, which is longer than the specified 500
Created a chunk of size 1483, which is longer than the specified 500
Created a chunk of size 1135, which is longer than the specified 500
Created a chunk of size 722, which is longer than the specified 500
Created a chunk of size 668, which is longer than the specified 500
Created a chunk of size 765, which is longer than the specified 500
Created a chunk of size 606, which is longer than the specified 500
Created a chunk of size 570, which is longer than the specified 500
Created a chunk of size 965, which is longer than the specified 500
Created a chunk of size 857, which is longer than the specified 500
Created a chunk of size 1032, which is longer than the specified 500
Created a chunk of size 652, which is longer than the specified 500
Created a chunk of size 733, which is longer than the specified 500
Created a chunk of size 525, which is longer than the specified 500
Created a chunk of size 1015, which is longer than the specified 500
Created a chunk of size 970, which is longer than the specified 500
Created a chunk of size 688, which is longer than the specified 500
Created a chunk of size 544, which is longer than the specified 500
Created a chunk of size 931, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 749, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 704, which is longer than the specified 500
Created a chunk of size 1912, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 556, which is longer than the specified 500
Created a chunk of size 624, which is longer than the specified 500
Created a chunk of size 2616, which is longer than the specified 500
Created a chunk of size 1580, which is longer than the specified 500
Created a chunk of size 994, which is longer than the specified 500
Created a chunk of size 847, which is longer than the specified 500
Created a chunk of size 1530, which is longer than the specified 500
Created a chunk of size 2030, which is longer than the specified 500
Created a chunk of size 1619, which is longer than the specified 500
Created a chunk of size 698, which is longer than the specified 500
Created a chunk of size 822, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 1189, which is longer than the specified 500
Created a chunk of size 508, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 1282, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 1277, which is longer than the specified 500
Created a chunk of size 1056, which is longer than the specified 500
Created a chunk of size 784, which is longer than the specified 500
Created a chunk of size 969, which is longer than the specified 500
Created a chunk of size 613, which is longer than the specified 500
Created a chunk of size 757, which is longer than the specified 500
Created a chunk of size 963, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 786, which is longer than the specified 500
Created a chunk of size 648, which is longer than the specified 500
Created a chunk of size 984, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 1163, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 875, which is longer than the specified 500
Created a chunk of size 817, which is longer than the specified 500
Created a chunk of size 755, which is longer than the specified 500
Created a chunk of size 569, which is longer than the specified 500
Created a chunk of size 628, which is longer than the specified 500
Created a chunk of size 868, which is longer than the specified 500
Created a chunk of size 620, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 1084, which is longer than the specified 500
Created a chunk of size 2762, which is longer than the specified 500
Created a chunk of size 1033, which is longer than the specified 500
Created a chunk of size 758, which is longer than the specified 500
Created a chunk of size 773, which is longer than the specified 500
Created a chunk of size 634, which is longer than the specified 500
Created a chunk of size 1010, which is longer than the specified 500
Created a chunk of size 1064, which is longer than the specified 500
Created a chunk of size 795, which is longer than the specified 500
Created a chunk of size 699, which is longer than the specified 500
Created a chunk of size 1224, which is longer than the specified 500
Created a chunk of size 657, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 553, which is longer than the specified 500
Created a chunk of size 590, which is longer than the specified 500
Created a chunk of size 726, which is longer than the specified 500
Created a chunk of size 1805, which is longer than the specified 500
Created a chunk of size 1017, which is longer than the specified 500
Created a chunk of size 684, which is longer than the specified 500
Created a chunk of size 739, which is longer than the specified 500
Created a chunk of size 922, which is longer than the specified 500
Created a chunk of size 967, which is longer than the specified 500
Created a chunk of size 645, which is longer than the specified 500
Created a chunk of size 676, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 670, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 760, which is longer than the specified 500
Created a chunk of size 796, which is longer than the specified 500
Created a chunk of size 679, which is longer than the specified 500
Created a chunk of size 927, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 733, which is longer than the specified 500
Created a chunk of size 868, which is longer than the specified 500
Created a chunk of size 931, which is longer than the specified 500
Created a chunk of size 772, which is longer than the specified 500
Created a chunk of size 770, which is longer than the specified 500
Created a chunk of size 649, which is longer than the specified 500
Created a chunk of size 1771, which is longer than the specified 500
Created a chunk of size 534, which is longer than the specified 500
Created a chunk of size 824, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 969, which is longer than the specified 500
Created a chunk of size 554, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 670, which is longer than the specified 500
Created a chunk of size 707, which is longer than the specified 500
Created a chunk of size 654, which is longer than the specified 500
Created a chunk of size 1270, which is longer than the specified 500
Created a chunk of size 736, which is longer than the specified 500
Created a chunk of size 1019, which is longer than the specified 500
Created a chunk of size 777, which is longer than the specified 500
Created a chunk of size 682, which is longer than the specified 500
Created a chunk of size 598, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 857, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 537, which is longer than the specified 500
Created a chunk of size 567, which is longer than the specified 500
Created a chunk of size 705, which is longer than the specified 500
Created a chunk of size 848, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 1177, which is longer than the specified 500
Created a chunk of size 904, which is longer than the specified 500
Created a chunk of size 852, which is longer than the specified 500
Created a chunk of size 507, which is longer than the specified 500
Created a chunk of size 1715, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 1681, which is longer than the specified 500
Created a chunk of size 721, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 603, which is longer than the specified 500
Created a chunk of size 991, which is longer than the specified 500
Created a chunk of size 1128, which is longer than the specified 500
Created a chunk of size 2005, which is longer than the specified 500
Created a chunk of size 1171, which is longer than the specified 500
Created a chunk of size 2141, which is longer than the specified 500
Created a chunk of size 662, which is longer than the specified 500
Created a chunk of size 1322, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 1112, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 908, which is longer than the specified 500
Created a chunk of size 1316, which is longer than the specified 500
Created a chunk of size 691, which is longer than the specified 500
Created a chunk of size 950, which is longer than the specified 500
Created a chunk of size 1121, which is longer than the specified 500
Created a chunk of size 776, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 1018, which is longer than the specified 500
Created a chunk of size 725, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 629, which is longer than the specified 500
Created a chunk of size 1007, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 884, which is longer than the specified 500
Created a chunk of size 579, which is longer than the specified 500
Created a chunk of size 911, which is longer than the specified 500
Created a chunk of size 1057, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 1255, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 1098, which is longer than the specified 500
Created a chunk of size 907, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500

In [6]:
print(len(documents))

4415

In [7]:
print(documents[0])

page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.' metadata={'source': '../tagged_description.txt'}

In [8]:
embedding_model = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(
    documents,
    embedding=embedding_model
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
query = "A book to teach children about nature"

docs = db_books.similarity_search(query, k=10)

docs

[Document(id='91da700f-e6c2-4867-afec-9c16f057dfd2', metadata={'source': '../tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='89e88e7f-23a6-4455-ae87-1ba9e9f35859', metadata={'source': '../tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='fe46254c-3ffc-47b7-8c93-66de4d576045', metadata={'source': '../tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='d6ee512e-6af1-4df6-bbf4-29d46a7597bb', metadata={'source': '../tagged_description.txt'}, page_content="9780060959036 Barbara Kingsolver's fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel's intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."),
 Document(id='3e851b28-6d10-4504-91aa-3b778f3de994', metadata={'source': '../tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='083c23f2-b154-4d29-b482-b9652b6eb430', metadata={'source': '../tagged_description.txt'}, page_content="9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."),
 Document(id='74011949-a559-4182-9eb0-298c3ca71692', metadata={'source': '../tagged_description.txt'}, page_content='9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub.'),
 Document(id='6561da15-bdcd-4256-bf2e-4de20ebe09a9', metadata={'source': '../tagged_description.txt'}, page_content="9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author's father].' 'BL. 1986 Children's Editors' Choices (BL) Children's Choices for 1987 (IRA/CBC) Notable 1986 Childrens' Trade Books in Social Studies (NCSS/CBC) 1986 Children's Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"),
 Document(id='a5ead7d7-b394-4e0a-b9f7-9a93b66e3d83', metadata={'source': '../tagged_description.txt'}, page_content='"9781593851170 ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."'),
 Document(id='8e70f721-4282-46ea-b9aa-53accd56aab6', metadata={'source': '../tagged_description.txt'}, page_content="9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat's community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it's hard to evade questions forever. Children's Choices for 1991 (IRA/CBC)VOYA's Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award")]

In [10]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [11]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:

    recs = db_books.similarity_search(query, k=50)

    books_list = []

    for rec in recs:
        isbn = int(rec.page_content.strip('"').split()[0])
        books_list.append(isbn)

    return books[books["isbn13"].isin(books_list)]

In [12]:
retrieve_semantic_recommendations("a book about world war")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
66,9780007162994,0007162995,If I Die in a Combat Zone,Tim O'Brien,"Vietnam War, 1961-1975",http://books.google.com/books/content?id=0qUtS...,Perhaps the best book to emerge from the Vietn...,2003.0,3.95,208.0,11.0,If I Die in a Combat Zone,9780007162994 Perhaps the best book to emerge ...
124,9780060516055,0060516054,What Went Wrong?,Bernard Lewis,History,http://books.google.com/books/content?id=qgNrV...,"For centuries, the world of Islam was in the f...",2003.0,3.49,186.0,2409.0,What Went Wrong?: The Clash Between Islam and ...,"9780060516055 For centuries, the world of Isla..."
254,9780060841867,0060841869,The Curtain,Milan Kundera,Literary Collections,http://books.google.com/books/content?id=JCDXP...,Traces the author's personal view of the histo...,2006.0,3.96,176.0,1351.0,The Curtain: An Essay in Seven Parts,9780060841867 Traces the author's personal vie...
461,9780099273868,0099273861,The Great World,David Malouf,Australia,http://books.google.com/books/content?id=f8IiK...,"""Every city, town and village has its memorial...",1999.0,3.87,336.0,514.0,The Great World,"9780099273868 ""Every city, town and village ha..."
524,9780099483472,0099483475,All Quiet on the Western Front,Erich Maria Remarque,"World War, 1914-1918",NaN,All Quiet on the Western Front is probably the...,2005.0,3.95,216.0,1018.0,All Quiet on the Western Front,9780099483472 All Quiet on the Western Front i...
541,9780099910107,0099910101,A Farewell to Arms,Ernest Hemingway,War,http://books.google.com/books/content?id=m68Lh...,"In 1918 Ernest Hemingway went to war, to the '...",1994.0,3.80,293.0,210197.0,A Farewell to Arms,9780099910107 In 1918 Ernest Hemingway went to...
572,9780140149241,0140149244,We Were the Rats,Lawson Glassop,"Tobruk, Battles of, 1941-1942",NaN,Reissue of the famous novel based on the autho...,1991.0,3.23,275.0,13.0,We Were the Rats,9780140149241 Reissue of the famous novel base...
574,9780140152746,0140152741,Mao II,Don DeLillo,Fiction,http://books.google.com/books/content?id=t0v7j...,Reclusive writer Bill Gray escapes his failed ...,1992.0,3.68,254.0,8085.0,Mao II,9780140152746 Reclusive writer Bill Gray escap...
795,9780142002803,0142002801,"The Fall of Berlin, 1945",Antony Beevor,History,http://books.google.com/books/content?id=u6avD...,Chronicles the horror of Berlin's fall to the ...,2003.0,4.28,490.0,9635.0,"The Fall of Berlin, 1945",9780142002803 Chronicles the horror of Berlin'...
859,9780143037576,0143037579,Fear and Trembling,Søren Kierkegaard,Philosophy,http://books.google.com/books/content?id=acFp6...,"The perfect books for the true book lover, Pen...",2005.0,4.00,160.0,13333.0,Fear and Trembling,9780143037576 The perfect books for the true b...
875,9780143104827,0143104829,Life is a Dream,Pedro Calderón de la Barca,Drama,http://books.google.com/books/content?id=yZ3eI...,Considered one of the outstanding Spanish dram...,2006.0,3.98,160.0,154.0,Life is a Dream,9780143104827 Considered one of the outstandin...
955,9780192822895,0192822896,La Débâcle,Emile Zola;Elinor Dorday;Robert Lethbridge,Fiction,http://books.google.com/books/content?id=GxNnS...,Zola wrote that 'my title speaks not merely of...,2000.0,3.99,592.0,763.0,La Débâcle,9780192822895 Zola wrote that 'my title speaks...
1127,9780306805622,0306805626,The Collapse of the Third Republic,William Lawrence Shirer,History,http://books.google.com/books/content?id=IdyBP...,"On June 17, 1940 William L. Shirer stood in th...",1994.0,4.20,1082.0,497.0,The Collapse of the Third Republic: An Inquiry...,"9780306805622 On June 17, 1940 William L. Shir..."
1199,9780312265052,0312265050,The Naked and the Dead,Norman Mailer,Fiction,http://books.google.com/books/content?id=c66GL...,Portrays the contrasting personalities and nos...,2000.0,3.94,721.0,20541.0,The Naked and the Dead: 50th Anniversary Editi...,9780312265052 Portrays the contrasting persona...
1262,9780312424671,0312424671,Small Island,Andrea Levy,Fiction,http://books.google.com/books/content?id=tahyl...,At the end of World War II the Joseph family a...,2004.0,3.93,441.0,20087.0,Small Island: A Novel,9780312424671 At the end of World War II the J...
1268,9780312426118,0312426119,A Woman in Berlin,Anonymous,Biography & Autobiography,http://books.google.com/books/content?id=HcrzD...,A wartime journal by a reporter and editor liv...,2006.0,4.32,261.0,5754.0,A Woman in Berlin: Eight Weeks in the Conquere...,9780312426118 A wartime journal by a reporter ...
1386,9780330340199,0330340190,In Pharaoh's Army,Tobias Wolff,"Authors, American",http://books.google.com/books/content?id=TO77D...,Having survived the extraordinary childhood re...,1995.0,4.08,224.0,21.0,In Pharaoh's Army: Memories of a Lost War,9780330340199 Having survived the extraordinar...
1429,9780340774779,0340774770,"The Road to War, 1933-1939",Andrew Hunt,Germany,http://books.google.com/books/content?id=YYLPG...,This text uses a source-based approach to stud...,2000.0,0.00,128.0,0.0,"The Road to War, 1933-1939",9780340774779 This text uses a source-based ap...
1493,9780345441300,0345441303,My Movie Business,John Irving,Biography & Autobiography,http://books.google.com/books/content?id=l1Hoy...,The author of The World According to Garp and ...,2000.0,3.33,222.0,1098.0,My Movie Business: A Memoir,9780345441300 The author of The World Accordin...
1522,9780345461360,0345461363,To The Last Man,Jeff Shaara,Fiction,http://books.google.com/books/content?id=YLTBB...,"In the spring of 1918, when a neutral America ...",2005.0,4.22,636.0,4656.0,To The Last Man: A Novel Of The First World War,"9780345461360 In the spring of 1918, when a ne..."
1688,9780375706363,0375706364,Crucible of War,Fred Anderson,History,http://books.google.com/books/content?id=jyuMq...,"Demonstrating that the decisive ""Seven Years' ...",2000.0,4.15,912.0,2968.0,Crucible of War: The Seven Years' War and the ...,9780375706363 Demonstrating that the decisive ...
1735,9780375760525,0375760520,Paris 1919,Margaret MacMillan,History,http://books.google.com/books/content?id=5NYdw...,National Bestseller New York Times Editors’ Ch...,2002.0,4.07,570.0,9150.0,Paris 1919: Six Months That Changed the World,9780375760525 National Bestseller New York Tim...
1825,9780385336956,0385336950,The Cloud Atlas,Liam Callanan,Fiction,http://books.google.com/books/content?id=S828t...,"During World War II, Louis Belk, a young Ameri...",2004.0,3.37,368.0,1697.0,The Cloud Atlas,"9780385336956 During World War II, Louis Belk,..."
2176,9780440227533,0440227534,Number the Stars,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=IMZWo...,"In 1943, during the German occupation of Denma...",1989.0,4.13,137.0,379669.0,Number the Stars,"9780440227533 In 1943, during the German occup..."
2370,9780451207791,0451207793,The Key to Rebecca,Ken Follett,Fiction,http://books.google.com/books/content?id=BGxfA...,"While Rommel's army bears down on Cairo, a rut...",2003.0,3.88,352.0,18661.0,The Key to Rebecca,9780451207791 While Rommel's army bears down o...
2372,9780451208705,0451208706,The Man from St. Petersburg,Ken Follett,Fiction,http://books.google.com/books/content?id=dTA7D...,"Just before World War I, two men--one a noble ...",2003.0,3.87,320.0,15320.0,The Man from St. Petersburg,"9780451208705 Just before World War I, two men..."
2828,9780571207992,0571207995,The Wars,Timothy Findley,Fiction,http://books.google.com/books/content?id=AqnDQ...,"Robert Ross, a sensitive nineteen-year-old Can...",2001.0,3.87,218.0,6229.0,The Wars,"9780571207992 Robert Ross, a sensitive ninetee..."
2829,9780571209057,057120905X,Famous Last Words,Timothy Findley,Prisoners of war,http://books.google.com/books/content?id=XwOkQ...,"In the final days of the Second World War, Hug...",2001.0,3.99,416.0,1348.0,Famous Last Words,9780571209057 In the final days of the Second ...
2843,9780575073357,0575073357,The Man in the High Castle,Philip K. Dick,Alternative histories (Fiction),http://books.google.com/books/content?id=8HBAP...,It is 1962 and the Second World War has been o...,2001.0,3.63,256.0,437.0,The Man in the High Castle,9780575073357 It is 1962 and the Second World ...
2930,9780618574810,0618574816,Tolkien And The Great War,John Garth,Biography & Autobiography,http://books.google.com/books/content?id=OODLV...,The author focuses on a little-discussed aspec...,2005.0,3.70,398.0,6167.0,Tolkien And The Great War: The Threshold Of Mi...,9780618574810 The author focuses on a little-d...
3058,9780679431367,0679431365,The Sword of Honour Trilogy,Evelyn Waugh,Fiction,http://books.google.com/books/content?id=kSQCA...,(Book Jacket Status: Jacketed) This trilogy of...,1994.0,4.24,711.0,1068.0,The Sword of Honour Trilogy,9780679431367 (Book Jacket Status: Jacketed) T...
3139,9780684813219,0684813211,Achilles in Vietnam,Jonathan Shay,Psychology,http://books.google.com/books/content?id=6EEnD...,An original and groundbreaking book that exami...,1994.0,4.24,272.0,1057.0,Achilles in Vietnam: Combat Trauma and the Und...,9780684813219 An original and groundbreaking b...
3154,9780684844077,0684844079,Soul of the Sword,Robert L. O'Connell,Technology & Engineering,http://books.google.com/books/content?id=eoEag...,A sweeping illustrated history of war and the ...,2002.0,4.08,400.0,36.0,Soul of the Sword: An Illustrated History of W...,9780684844077 A sweeping illustrated history o...
3180,9780688085872,0688085873,A Short History of World War II,James L. Stokesbury,History,http://books.google.com/books/content?id=uDBhl...,"Despite the numerous books on World War II, un...",1980.0,3.93,416.0,454.0,A Short History of World War II,9780688085872 Despite the numerous books on Wo...
3309,9780743223850,0743223853,Yanks,John Eisenhower,History,http://books.google.com/books/content?id=4UjYA...,"In the perfect match of subject and author, Jo...",2002.0,3.69,368.0,104.0,Yanks: The Epic Story of the American Army in ...,9780743223850 In the perfect match of subject ...
3331,9780743253970,0743253973,A Separate Peace,John Knowles,Fiction,http://books.google.com/books/content?id=MXodm...,An American classic and great bestseller for o...,2003.0,3.57,208.0,169719.0,A Separate Peace,9780743253970 An American classic and great be...
3614,9780764586712,0764586718,CliffsNotes on Remarque's All Quiet on the Wes...,Susan Van Kirk,Literary Criticism,http://books.google.com/books/content?id=AUTeK...,The original CliffsNotes study guides offer ex...,2001.0,4.24,112.0,12.0,CliffsNotes on Remarque's All Quiet on the Wes...,9780764586712 The original CliffsNotes study g...
3785,9780786937707,078693770X,Love and War,Margaret Weis;Tracy Hickman,Fiction,http://books.google.com/books/content?id=nFlxG...,This anthology collects tales of love and war ...,2005.0,3.88,368.0,43.0,Love and War,9780786937707 This anthology collects tales of...
3810,9780801870569,0801870569,Berlin Diary,William L. Shirer,Biography & Autobiography,http://books.google.com/books/content?id=ExOVU...,By the acclaimed journalist and bestselling au...,2002.0,4.29,627.0,3494.0,Berlin Diary: The Journal of a Foreign Corresp...,9780801870569 By the acclaimed journalist and ...
3832,9780802151803,0802151809,Sexus,Henry Miller,Fiction,http://books.google.com/books/content?id=jzjwv...,"The first novel of Miller's frank, autobiograp...",1987.0,4.04,506.0,7024.0,Sexus: The Rosy Crucifixion I,9780802151803 The first novel of Miller's fran...
4053,9780822008934,0822008939,CliffsNotes on Wiesel's Night,Maryam Riess,Literary Criticism,http://books.google.com/books/content?id=sMetB...,The original CliffsNotes study guides offer ex...,1996.0,3.40,80.0,5.0,CliffsNotes on Wiesel's Night,9780822008934 The original CliffsNotes study g...
4056,9780822012375,0822012375,CliffsNotes on Hemingway's The Sun Also Rises,Gary Carey,Literary Criticism,http://books.google.com/books/content?id=6TBr9...,This is the book that chronicled the lives and...,1968.0,3.54,80.0,13.0,CliffsNotes on Hemingway's The Sun Also Rises,9780822012375 This is the book that chronicled...
4414,9781401204105,1401204104,The Sgt. Rock Archives,Robert Kanigher;Bob Haney,Comics & Graphic Novels,http://books.google.com/books/content?id=MnWYK...,"An intense portrait of combat and conflict, th...",2005.0,4.56,224.0,18.0,The Sgt. Rock Archives,9781401204105 An intense portrait of combat an...
4644,9781565842212,1565842219,The War,Marguerite Duras,Biography & Autobiography,http://books.google.com/books/content?id=1h1uP...,"The extraordinary pages of The War, written in...",1994.0,3.85,192.0,918.0,The War: A Memoir,9781565842212 The extraordinary pages of The W...
4647,9781565847040,1565847040,Dr. Seuss Goes to War,Richard H. Minear;Dr. Seuss,History,http://books.google.com/books/content?id=2p2qD...,"For decades, readers throughout the world have...",2001.0,4.18,272.0,1225.0,Dr. Seuss Goes to War: The World War II Editor...,"9781565847040 For decades, readers throughout ..."
4651,9781566633949,156663394X,Complete Essays,Aldous Huxley,English essays,http://books.google.com/books/content?id=t1Efz...,The fourth of six volumes collects essays that...,2001.0,4.33,416.0,6.0,Complete Essays,9781566633949 The fourth of six volumes collec...
4656,9781567921588,1567921582,"W, Or, The Memory of Childhood",Georges Perec,Fiction,http://books.google.com/books/content?id=vuN10...,Guaranteed to send shock waves through the lit...,2003.0,3.88,176.0,1395.0,"W, Or, The Memory of Childhood",9781567921588 Guaranteed to send shock waves t...
4794,9781585672790,1585672793,This Is Berlin,William L. Shirer;John Keegan,History,http://books.google.com/books/content?id=PbmLP...,Collects two-and-a-half years of the author's ...,2002.0,4.22,478.0,147.0,This Is Berlin: Radio Broadcasts from Nazi Ger...,9781585672790 Collects two-and-a-half years of...
4843,9781590302255,1590302257,The Art of War,Sun-Tzu;Sunzi,Philosophy,http://books.google.com/books/content?id=Kjw1j...,"Written around the 6th century BC, The Art of ...",2005.0,3.97,273.0,214954.0,The Art of War,9781590302255 Written around the 6th century B...
5015,9781845203344,1845203348,The Intelligence of Evil or the Lucidity Pact,Jean Baudrillard,Philosophy,http://books.google.com/books/content?id=jNxzQ...,There are few philosophers today cool enough t...,2005.0,3.86,215.0,239.0,The Intelligence of Evil or the Lucidity Pact,9781845203344 There are few philosophers today...